In [3]:
dict = {'Name': 'Zabra', 'Age': 7}

#This method return a value for the given key. If key is not available, then returns default value None.
print ("Value : %s" %  dict.get('Education'))

#print "Value : %s" %  dict.get('Education', "Never")

Value : None


In [ ]:
def text_to_ids(source_text, target_text, source_vocab_to_int, target_vocab_to_int):
    """
    Convert source and target text to proper word ids
    :param source_text: String that contains all the source text.
    :param target_text: String that contains all the target text.
    :param source_vocab_to_int: Dictionary to go from the source words to an id
    :param target_vocab_to_int: Dictionary to go from the target words to an id
    :return: A tuple of lists (source_id_text, target_id_text)
    """
    # TODO: Implement Function        
    source_id_text = [[source_vocab_to_int.get(word, source_vocab_to_int['<EOS>']) for word in sentence] for sentence in source_text.split('\n')]
    target_id_text = [[target_vocab_to_int.get(word, target_vocab_to_int['<EOS>']) for word in sentence] for sentence in target_text.split('\n')]
    
    return source_id_text, target_id_text

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_text_to_ids(text_to_ids)

In [ ]:
for line in source_sentences.split('\n'):
    for letter in line:
        Source_letter_ids = [[source_letter_to_int.get(letter, source_letter_to_int[''])]]

In [17]:
import tensorflow as tf

t1 = [[1,2,3], [4,5,6], [7,8,9]]
t2 = [[7,8,9], [10,11,12], [13,14,15]]
t3 = tf.concat([t1, t2], 0) 
t4 = tf.concat([t1, t2], 1) 
#t5 = tf.concat([t1, t2], 2)
sess = tf.Session()
print(t1)
print(t2)
print(sess.run(t3))
print(sess.run(t4))
#print(sess.run(t5))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[7, 8, 9], [10, 11, 12], [13, 14, 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]
 [ 7  8  9 13 14 15]]


In [3]:
import tensorflow as tf
input = [[[1,1,1],[2,2,2],[3,3,3]],
         [[4,4,4],[5,5,5],[6,6,6]],
         [[7,7,7],[8,8,8],[9,9,9]]]

sess = tf.Session()

a = tf.slice(input, [0,1,0], [2,2,2])
print(sess.run(a))
print("\n")

b = tf.strided_slice(input, [0,1,0], [2,3,2], [1,1,1])
print(sess.run(b))

[[[2 2]
  [3 3]]

 [[5 5]
  [6 6]]]


[[[2 2]
  [3 3]]

 [[5 5]
  [6 6]]]


In [23]:
import tensorflow as tf
import numpy as np

t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
t3 = [[13, 14, 15], [16, 17, 18]]

sess = tf.Session()

a1 = tf.concat([t1, t2, t3], 0)
a2 = tf.concat([t1, t2, t3], 1)

b1 = np.concatenate((t1, t2), 0)
b2 = np.concatenate((t1, t2), 1)

print(sess.run(a1))
print("\n")
#print(b1)
#print("\n")

print(sess.run(a2))
#print("\n")
#print(b2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


In [12]:
a3 = tf.concat([t1, t2], 2)

ValueError: Shape must be at least rank 3 but is rank 2 for 'concat_14' (op: 'ConcatV2') with input shapes: [2,3], [2,3], [].

In [20]:
import tensorflow as tf
t1 = tf.fill([2,3,4], 3, name=None)
sess = tf.Session()

print(sess.run())

[]


In [ ]:
t